name: Approve Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
